package sms.gradle.utils;

import java.util.List;

public final class DatabaseTableData {

    public static final List<String> FIRST_NAMES = List.of(
            "John",
            "Jane",
            "Michael",
            "Emily",
            "David",
            "Sarah",
            "Robert",
            "Emma",
            "William",
            "Olivia",
            "James",
            "Ava",
            "Alexander",
            "Sophia",
            "Benjamin",
            "Isabella",
            "Daniel",
            "Mia",
            "Matthew",
            "Charlotte",
            "Ethan",
            "Abigail",
            "Joseph",
            "Harper",
            "Jackson",
            "Amelia",
            "Aiden",
            "Evelyn",
            "Samuel",
            "Elizabeth",
            "Lucas",
            "Sofia",
            "Henry",
            "Avery",
            "Sebastian",
            "Ella",
            "Owen",
            "Scarlett",
            "Gabriel",
            "Grace",
            "Carter",
            "Chloe",
            "Jayden",
            "Riley",
            "Wyatt",
            "Lily",
            "Luke",
            "Aria",
            "Dylan",
            "Zoey",
            "Levi",
            "Hannah",
            "Nathan",
            "Lillian",
            "Isaac",
            "Addison",
            "Julian",
            "Nora",
            "Elijah",
            "Audrey",
            "Liam",
            "Brooklyn",
            "Mason",
            "Savannah",
            "Logan",
            "Claire",
            "Oliver",
            "Skylar",
            "Caleb",
            "Eleanor");

    public static final List<String> LAST_NAMES = List.of(
            "Smith",
            "Johnson",
            "Williams",
            "Brown",
            "Jones",
            "Garcia",
            "Miller",
            "Davis",
            "Rodriguez",
            "Martinez",
            "Hernandez",
            "Lopez",
            "Gonzalez",
            "Wilson",
            "Anderson",
            "Thomas",
            "Taylor",
            "Moore",
            "Jackson",
            "Martin",
            "Lee",
            "Perez",
            "Thompson",
            "White",
            "Harris",
            "Sanchez",
            "Clark",
            "Ramirez",
            "Lewis",
            "Robinson",
            "Walker",
            "Young",
            "Allen",
            "King",
            "Wright",
            "Scott",
            "Torres",
            "Nguyen",
            "Hill",
            "Flores",
            "Green",
            "Adams",
            "Nelson",
            "Baker",
            "Hall",
            "Rivera",
            "Campbell",
            "Mitchell",
            "Carter",
            "Roberts",
            "Phillips",
            "Evans",
            "Turner",
            "Torres",
            "Parker",
            "Collins",
            "Edwards",
            "Stewart",
            "Flores",
            "Morris");

    public static final List<String> COURSE_NAMES = List.of(
            "Computer Science",
            "Mathematics",
            "Physics",
            "Chemistry",
            "Biology",
            "English",
            "History",
            "Geography",
            "Literature",
            "Art",
            "Music",
            "Physical Education",
            "Economics",
            "Psychology",
            "Sociology",
            "Political Science",
            "Philosophy",
            "Business",
            "Marketing",
            "Finance",
            "Information Technology",
            "Engineering",
            "Medicine",
            "Nursing",
            "Law",
            "Education",
            "Communication",
            "Environmental Science",
            "Agriculture",
            "Architecture",
            "Film Studies",
            "Culinary Arts",
            "Journalism",
            "Social Work",
            "Counseling",
            "Health Science",
            "Nutrition",
            "Dentistry",
            "Veterinary Medicine",
            "Pharmacy",
            "Astronomy",
            "Astrophysics",
            "Astrobiology",
            "Astrochemistry",
            "Astrogeology",
            "Astrology",
            "Astrocartography",
            "Astroentomology",
            "Astroethnology",
            "Astroephemery");

    public static final List<String> MODULE_NAMES = List.of(
            "Introduction",
            "Fundamentals",
            "Advanced",
            "Practical",
            "Theory",
            "Application",
            "Design",
            "Implementation",
            "Analysis",
            "Evaluation",
            "Management",
            "Strategy",
            "Planning",
            "Control",
            "Measurement",
            "Simulation",
            "Optimization",
            "Evaluation",
            "Innovation",
            "Integration",
            "Communication",
            "Collaboration",
            "Leadership",
            "Teamwork",
            "Problem Solving",
            "Critical Thinking",
            "Creativity",
            "Innovation",
            "Risk Management",
            "Quality Control",
            "Process Improvement",
            "Cost Analysis",
            "Budgeting",
            "Resource Management",
            "Supply Chain",
            "Logistics",
            "Inventory Management",
            "Order Fulfillment",
            "Warehouse Management",
            "Transportation Management",
            "Project Management",
            "Risk Management",
            "Compliance Management",
            "Regulatory Management",
            "Risk Assessment",
            "Risk Mitigation",
            "Risk Transfer",
            "Risk Communication",
            "Risk Awareness");
}
