classDiagram
    class AdminDAO {
        -AdminDAO()
        +addAdmin(admin)
        +findById(id)
        +findByEmail(email)
        +findAll()
        +update(admin)
        +delete(id)

        -getAdminFromResultSet()
        -getOptionalAdminFromResultSet()
    }