classDiagram
    class StudentDAO {
        -StudentDAO()
        +addStudent(student, password)
        +findById(id)
        +findByEmail(name)
        +findAll()
        +update(student)
        +delete(id)

        -getStudentFromResultSet()
        -getOptionalStudentFromResultSet()
    }