classDiagram
    class Assessment {
      -int id
      -String name
      -String description
      -Date dueDate
      -int moduleId

      +getId()
      +getName()
      +setName()
      +getDescription()
      +setDescription()
      +getDueDate()
      +setDueDate()
      +getModuleId()
    }