classDiagram
    class Module {
      -int id
      -String name
      -String description
      -String lecturer
      -int courseId

      +getId()
      +getName()
      +setName()
      +getDescription()
      +setDescription()
      +getLecturer()
      +setLecturer()
      +getCourseId()
    }