classDiagram
    class Student {
      -int id
      -String firstName
      -String lastName
      -String email
      -Date dateOfBirth
      -Date joinDate

      +getId()
      +getFirstName()
      +setFirstName()
      +getLastName()
      +setLastName()
      +getEmail()
      +setEmail()
      +getDateOfBirth()
      +setDateOfBirth()
      +getJoinDate()
      +setJoinDate()
    }