classDiagram
    class Module {
      -int id
      -String name
      -String description
      -String lectuer
      -int courseId

      +getId()
      +getName()
      +setName()
      +getDescription()
      +setDescription()
      +getLectuer()
      +setLectuer()
      +getCourseId()
    }