/*
 * This source file was generated by the Gradle 'init' task
 */
package sms.gradle;

import sms.gradle.model.dao.DatabaseConnection;

public class App {
    public static void main(String[] args) {
        DatabaseConnection dbConnection = DatabaseConnection.getInstance();
    }
}
