classDiagram
    class CourseEnrollment {
      -int id
      -int studentId
      -int courseId
      -Date enrollmentDate

      +getId()
      +getStudentId()
      +getCourseId()
      +getEnrollmentDate()
    }