name: Release on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean fatJar

      - name: Get Latest Release Number
        id: get_latest_release
        run: |
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "0")
          RELEASE_NUM=$(echo $LATEST_TAG | grep -o '[0-9]*' || echo "0")
          NEW_RELEASE_NUM=$((RELEASE_NUM + 1))
          echo "NEW_VERSION=$NEW_RELEASE_NUM" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: "release-${{ env.NEW_VERSION }}"
          name: "Release ${{ env.NEW_VERSION }}"
          draft: false
          prerelease: false
          files: app/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}