name: Release on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Fat JAR
        run: ./gradlew fatJar

      - name: Create Run Scripts
        run: |
          # Create run.sh
          echo '#!/bin/bash
          java -jar StudentManagementSystem-fat.jar' > run.sh
          
          # Create run.bat
          echo '@echo off
          java -jar StudentManagementSystem-fat.jar
          pause' > run.bat
          
          # Make run.sh executable
          chmod +x run.sh

      - name: Create README
        run: |
          echo '# Student Management System

          ## Requirements
          - Java 21 or later

          ## Running the Application

          ### Option 1: Using Scripts
          #### Windows
          Double-click `run.bat`

          #### macOS/Linux
          Make the script executable (first time only):
          ```bash
          chmod +x run.sh
          ```
          Then run:
          ```bash
          ./run.sh
          ```

          ### Option 2: Direct Command
          From the command line:
          ```
          java -jar StudentManagementSystem-fat.jar
          ```

          ## Troubleshooting
          If you encounter any issues:
          1. Ensure Java 21 is installed and in your PATH
          2. Verify Java version by running: `java -version`
          3. Try running the direct command to see any error messages' > README.md

      - name: Get Latest Release Number
        id: get_latest_release
        run: |
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "0")
          RELEASE_NUM=$(echo $LATEST_TAG | grep -o '[0-9]*' || echo "0")
          NEW_RELEASE_NUM=$((RELEASE_NUM + 1))
          echo "NEW_VERSION=$NEW_RELEASE_NUM" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-${{ env.NEW_VERSION }}"
          name: "Release ${{ env.NEW_VERSION }}"
          body: |
            # Student Management System Release ${{ env.NEW_VERSION }}

            ## Quick Start
            1. Download the JAR file and run scripts
            2. Make sure Java 21 is installed
            3. Run using one of these methods:
               - Windows: Double-click `run.bat`
               - Mac/Linux: Run `./run.sh`
               - Any platform: `java -jar StudentManagementSystem-fat.jar`
            
            ## Requirements
            - Java 21 or later
            
            ## Files Included
            - StudentManagementSystem-fat.jar (Main application)
            - run.sh (Unix/Mac launcher)
            - run.bat (Windows launcher)
            - README.md (Instructions)

            ## Need Help?
            See README.md for detailed instructions and troubleshooting.
          draft: false
          prerelease: false
          files: |
            app/build/libs/*-fat.jar
            run.sh
            run.bat
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}